const path=require("path");
const repo="D:/Programs/github/lingua_1";
const root=path.join(repo,"electron_node/electron-node");
process.chdir(root); process.env.PROJECT_ROOT=repo;
const dist=path.join(root,"dist/main/electron-node/main/src");
const Database=require("better-sqlite3");
const {LexiconRuntimeV2}=require(path.join(dist,"lexicon-v2/lexicon-runtime-v2.js"));
const {defaultGeneralProfile}=require(path.join(dist,"lexicon-v2/profile-registry.js"));
const {resolveRecallScope}=require(path.join(dist,"lexicon-v2/resolve-recall-enabled-fine-domains.js"));
const {loadFwDetectorRuntimeConfig}=require(path.join(dist,"fw-detector/fw-config.js"));
const {recallSpanTopKV2}=require(path.join(dist,"lexicon-v2/recall-span-topk-v2.js"));
const db=new Database(path.join(repo,"node_runtime/lexicon/_rebuild_candidate/lexicon.sqlite"),{readonly:true});
const row=db.prepare("SELECT * FROM term WHERE word=?").get("迷你吧");
const dom=db.prepare("SELECT * FROM domain_lexicon WHERE word=?").all("迷你吧");
console.log("term", row);
console.log("dom", dom);
const rt=new LexiconRuntimeV2(); rt.loadFromBundleDir(path.join(repo,"node_runtime/lexicon/_rebuild_candidate"));
const fw=loadFwDetectorRuntimeConfig();
const profile=defaultGeneralProfile();
const domainIds=resolveRecallScope({configEnabledDomains:fw.enabledDomains}).domainIds;
const syl=String(row.pinyin_key).split("|");
const tones=String(row.tone_pinyin_key).split("|").map(p=>{const m=p.match(/([1-5])$/);return m?Number(m[1]):1;});
const r=recallSpanTopKV2(rt,{syllables:syl,windowText:"迷你吧",termLength:3,topK:5,perSpanLimit:5,profile,domainIds,acousticTonePattern:tones,toneCallerEnabled:true});
console.log("hits", r.hits.map(h=>({w:h.hotword.word,d:h.hotword.domains,p:h.hotword.priorScore})));
const base=rt.lookupBaseByPinyinKey(row.pinyin_key,3);
const dhit=rt.lookupDomainsByPinyinKeyMulti(domainIds,row.pinyin_key,3);
console.log("base", base.map(h=>h.word+"@"+h.priorScore));
console.log("domain", (dhit||[]).map(h=>h.word+"@"+h.priorScore+"@"+(h.domainId||h.domains)));
