const path=require("path");
const repo="D:/Programs/github/lingua_1";
const root=path.join(repo,"electron_node/electron-node");
process.chdir(root); process.env.PROJECT_ROOT=repo;
const dist=path.join(root,"dist/main/electron-node/main/src");
const {LexiconRuntimeV2}=require(path.join(dist,"lexicon-v2/lexicon-runtime-v2.js"));
const {defaultGeneralProfile}=require(path.join(dist,"lexicon-v2/profile-registry.js"));
const {resolveRecallScope}=require(path.join(dist,"lexicon-v2/resolve-recall-enabled-fine-domains.js"));
const {loadFwDetectorRuntimeConfig}=require(path.join(dist,"fw-detector/fw-config.js"));
const {buildUtteranceSyllableCoordinate}=require(path.join(dist,"fw-detector/pinyin-ime-v2/pinyin-ime-v2-pinyin-stream.js"));
const {loadPinyinImeV2RuntimeConfig}=require(path.join(dist,"fw-detector/pinyin-ime-v2/pinyin-ime-v2-config.js"));
const {loadPinyinImeV2Dictionaries,resolvePinyinImeV2DictDir}=require(path.join(dist,"fw-detector/pinyin-ime-v2/pinyin-ime-v2-dict-load.js"));
const {partitionCoarseSpans}=require(path.join(dist,"fw-detector/span-assembly-shared/coarse-span-partition.js"));
const {buildLexicalWindowQueries}=require(path.join(dist,"fw-detector/span-assembly-v4/build-lexical-window-queries.js"));
const {latticeHardBlockFilter}=require(path.join(dist,"fw-detector/span-assembly-v4/lattice-hard-block-filter.js"));
const {recallTopKForWindows}=require(path.join(dist,"fw-detector/span-assembly-v4/recall-topk-for-windows.js"));
const fw=loadFwDetectorRuntimeConfig();
const ime=loadPinyinImeV2RuntimeConfig();
const dict=loadPinyinImeV2Dictionaries(resolvePinyinImeV2DictDir(ime.dictDir),{enabledDomains:ime.enabledDomains});
const profile=defaultGeneralProfile();
const rt=new LexiconRuntimeV2();
rt.loadFromBundleDir(path.join(repo,"node_runtime/lexicon/_rebuild_candidate"));
const domainIds=resolveRecallScope({configEnabledDomains:fw.enabledDomains}).domainIds;
const surface="单元测试";
const coordinate=buildUtteranceSyllableCoordinate(surface);
const globalSyllables=coordinate.syllables;
console.log(JSON.stringify({syl:globalSyllables,minPrior:fw.minPrior,domains:domainIds.slice(0,8),nd:domainIds.length}));
const coarse=partitionCoarseSpans({rawText:surface,imeConfig:ime,dict}).coarseSpans;
const windows=buildLexicalWindowQueries({rawText:surface,globalSyllables,coarseSpans:coarse,charSyllableRanges:coordinate.ranges});
const filtered=latticeHardBlockFilter({windows,rawText:surface,coarseSpans:coarse,wordTimeSpans:[]});
const recallable=filtered.filter(w=>!w.blocked);
const fullWin=recallable.find(w=>w.syllableEnd-w.syllableStart===globalSyllables.length);
console.log(JSON.stringify({win:windows.length,recallable:recallable.length,fullWin:fullWin&&{id:fullWin.windowId,key:fullWin.windowPinyinKey,ss:fullWin.syllableStart,se:fullWin.syllableEnd}}));
const recall=recallTopKForWindows({rawText:surface,windows:recallable,globalSyllables:[...globalSyllables],runtime:rt,profile,domainIds,minPrior:fw.minPrior});
console.log("cand",recall.candidates.length);
const byWord={};
for (const c of recall.candidates) { const w=c.hotword?.word||"?"; byWord[w]=(byWord[w]||0)+1; }
console.log("top",Object.entries(byWord).sort((a,b)=>b[1]-a[1]).slice(0,20));
console.log("compound", recall.candidates.filter(c=>c.hotword?.word===surface).length);
const key=globalSyllables.join("|");
const base=rt.lookupBaseByPinyinKey(key, globalSyllables.length);
const dom=rt.lookupDomainsByPinyinKeyMulti(domainIds,key,globalSyllables.length);
console.log("directSurface", [...base,...(dom||[])].filter(h=>h.word===surface).map(h=>({w:h.word,p:h.priorScore,rt:h.repairTarget,d:h.domainId})));
console.log("baseLen",base.length,"domLen",(dom||[]).length,"baseSample",base.slice(0,5).map(h=>h.word+"@"+h.priorScore));
