"""Model2 V3 — Trainable user-conditioned retrieval policy.

Markers: MODEL2_V3_RETRIEVAL_POLICY / TRAINABLE_CORE_REQUIRED
"""

ARCHITECTURE_ID = "FINESPAN_USERPROFILE_TRAINABLE_RETRIEVAL_POLICY"
PREVIOUS_V2_NEURAL_VERDICT = "SUPERSEDED_BY_USER_ARCHITECTURE_DECISION"
