import type { NodeConfig } from './node-config-types';

/** 默认配置：所有 URL 等默认值仅在此定义，运行时由 electron-node-config.json 覆盖。 */
export const DEFAULT_CONFIG: NodeConfig = {
  servicePreferences: {},
  scheduler: { url: 'ws://127.0.0.1:5010/ws/node' },
  modelHub: { url: 'http://127.0.0.1:5000' },
  services: {
    baseUrl: 'http://127.0.0.1',
    phoneticCorrectionUrl: 'http://127.0.0.1:5016',
    punctuationRestoreUrl: 'http://127.0.0.1:5017',
  },
  testServer: { port: 5020 },
  lid: {
    enabled: true,
    modelPath: 'models/sherpa-onnx-lid',
    encoderFile: 'tiny-encoder.int8.onnx',
    decoderFile: 'tiny-decoder.int8.onnx',
  },
  metrics: {
    enabled: true,
    metrics: { rerun: true, asr: true },
  },
  asr: {
    engine: 'fw_detector_v1',
  },
  features: {
    enablePostProcessTranslation: true,
    enableS1PromptBias: false,
    enableS2Rescoring: false,
    phoneticCorrection: { enabled: false },
    semanticRepair: { enabled: false },
    punctuationRestore: { enabled: false },
    lexiconRecall: {
      enabled: false,
      maxReplacements: 2,
      recallMinPhoneticScore: 0.5,
      recallFuzzyPinyinMaxSyllableDelta: 2,
      expansionMinPhoneticScore: 0.5,
      selectionMinPhoneticScore: 0.85,
      maxSentenceCandidates: 32,
      multiWindowScoreEpsilon: 0.005,
      allowedWindowLengths: [2, 3, 4, 5],
      diffContextLeft: 2,
      diffContextRight: 2,
      topKByTermLength: { '2': 5, '3': 5, '4': 3, '5': 2 },
      maxActiveWindows: 2,
      minCandidateScore: 0,
      kenlmBaselineTolerance: 0.15,
      crossSegmentRecallEnabled: false,
      contractVersion: 'v5-scored-lexicon-topk',
    },
    lexiconV2: {
      enabled: false,
      sessionIntentWriteEnabled: false,
      intentEnabled: true,
      intentMode: 'cpu_llm',
      cpuWorker: {
        serviceUrl: 'http://127.0.0.1:5018',
        modelPath: 'models/lexicon-intent/qwen2.5-3b-instruct-q4_k_m.gguf',
        timeoutMs: 7500,
        promptPackVersion: 'v1',
        maxContextTurns: 20,
        maxSummaryChars: 300,
        metricsEnabled: true,
        warmupEnabled: true,
        warmupTimeoutMs: 120000,
        healthRefreshIntervalMs: 180000,
        recoveryEnabled: true,
        recoveryMaxRetries: 3,
        recoveryBackoffMs: [2000, 5000, 15000],
        recoveryRestartService: false,
      },
    },
    lexiconRuntimeV2: {
      enabled: true,
      bundlePath: 'node_runtime/lexicon/v3',
      lruBucketCacheSize: 512,
      maxBaseCandidates: 2,
      maxDomainCandidates: 3,
      maxIdiomCandidates: 0,
      recallDiagnosticsEnabled: true,
    },
    sessionAffinity: { enabled: true },
    fwDetector: {
      enabled: true,
      disableAsrRerun: true,
      minPrior: 0.5,
      enableKenLMGate: true,
      kenlmGateMode: 'weak_veto',
      /** @deprecated V4 rerank unused; kept for userData JSON compatibility */
      kenlmDeltaThreshold: 0.8,
      kenlmVetoThreshold: -0.2,
      enabledDomains: [],
      candidateRequireRepairTarget: true,
      useIndustryRouting: false,
      weakDomainRecallEnabled: false,
      fuzzyPinyinRecallEnabled: false,
      spanAssemblyV4Enabled: true,
      spanAssemblyV4DiagnosticsEnabled: false,
      spanAssemblyV4DiagnosticsLevel: 'summary',
      spanAssemblyV4DiagnosticsTargetIds: [],
      toneTimestampOnlyEnabled: true,
      maxSentenceCandidates: 16,
      minDeltaToReplace: 3.0,
      kenlmSubprocessTimeoutMs: 5000,
      kenlmSubprocessMaxLines: 17,
    },
    pinyinImeV2: {
      enabled: true,
      topK: 5,
      maxApprovedSpans: 4,
      minSupportCount: 2,
      minSpanChars: 2,
      maxSpanChars: 6,
      minSyllables: 2,
      maxSyllables: 5,
      directRepair: false,
      dictDir: 'node_runtime/pinyin-ime-v2/dict',
    },
  },
  textLength: {
    minLengthToKeep: 6,
    minLengthToSend: 20,
    maxLengthToWait: 40,
    waitTimeoutMs: 3000,
  },
};
