import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const PROJECT_ROOT = 'd:\\Programs\\github\\lingua_1';
const DIST = path.join(PROJECT_ROOT, 'electron_node', 'electron-node', 'dist', 'main', 'electron-node', 'main', 'src');
const OUT = path.join(PROJECT_ROOT, 'docs/user_correction/model3/_audit_probe3.txt');
fs.writeFileSync(OUT, 'start\n');
const { LexiconRuntimeV2 } = require(path.join(DIST, 'lexicon-v2/lexicon-runtime-v2.js'));
const { defaultGeneralProfile } = require(path.join(DIST, 'lexicon-v2/profile-registry.js'));
const { recallSpanTopKV2 } = require(path.join(DIST, 'lexicon-v2/recall-span-topk-v2.js'));
const { textToSyllables } = require(path.join(DIST, 'lexicon/phonetic/pinyin.js'));
const { textToToneSyllables } = require(path.join(DIST, 'lexicon/phonetic/tone-pinyin.js'));
const runtime = new LexiconRuntimeV2();
runtime.loadFromBundleDir(path.join(PROJECT_ROOT, 'node_runtime/lexicon/v3'));
const profile = defaultGeneralProfile();
fs.appendFileSync(OUT, 'loaded\n');
const w = '背';
const syl = textToSyllables(w);
const tonePat = textToToneSyllables(w).map((s) => Number((String(s).match(/([1-5])$/)||[])[1]||1));
const out = recallSpanTopKV2(runtime, { syllables: syl, windowText: w, termLength: 1, topK: 8, profile, domainIds: ['coffee'], perSpanLimit: 8, acousticTonePattern: tonePat });
fs.appendFileSync(OUT, 'recall ' + out.hits.map(h=>h.hotword.word).join(',') + '\n');
runtime.close?.();
console.log('done');
